- name: Join Worker Nodes to Kubernetes Cluster
  hosts: workers
  become: true

  tasks:
    - name: Wait for master node to be fully ready
      wait_for:
        host: "{{ hostvars['master']['ansible_host'] }}"
        port: 6443
        timeout: 300

    - name: Copy join command from local file
      copy:
        src: /tmp/k8s_join_command
        dest: /tmp/k8s_join_command
        mode: '0777'

    - name: Check if node is already part of cluster
      shell: kubectl --kubeconfig=/etc/kubernetes/kubelet.conf get nodes || echo "not_joined"
      register: node_status
      ignore_errors: true

    - name: Join the worker node to the cluster
      command: sh /tmp/k8s_join_command
      register: join_worker
      failed_when: join_worker.rc != 0 and "already exists" not in join_worker.stderr
      when: "'not_joined' in node_status.stdout"

    - name: Restart kubelet after join
      systemd:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Wait for kubelet to be active
      systemd:
        name: kubelet
        state: started
      register: kubelet_status
      until: kubelet_status.status.ActiveState == "active"
      retries: 10
      delay: 10

    - name: Verify node joined successfully
      shell: systemctl status kubelet
      register: kubelet_check

    - name: Display kubelet status
      debug:
        var: kubelet_check.stdout_lines
