---
- name: Join Worker Nodes to Kubernetes Cluster
  hosts: workers
  become: true

  tasks:
    - name: Copy join command from local file
      copy:
        src: /tmp/k8s_join_command
        dest: /tmp/k8s_join_command
        mode: '0777'

    - name: Join the worker node to the cluster
      command: sh /tmp/k8s_join_command
      register: join_worker
      failed_when: join_worker.rc != 0 and "already exists" not in join_worker.stderr

    - name: Configure kubelet to accept insecure registry
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        line: "Environment=\"KUBELET_EXTRA_ARGS=--feature-gates=AllAlpha=false\""
        insertafter: '\[Service\]'
        state: present
        create: yes

    - name: Restart kubelet
      systemd:
        name: kubelet
        daemon_reload: yes
        state: restarted
